/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Normalize strafe/forward input, rotate it by Minecraft yaw, and add it to
 * velocity without allocating any JavaScript objects.
 */
export declare function applyHeadingInto(strafe: number, forward: number, multiplier: number, yaw: number, velocity: Float64Array): void

/**
 * Resolve classic prismarine/node-aabb movement on all three axes in one call.
 * Inputs and output use [minX,minY,minZ,maxX,maxY,maxZ] and [x,y,z] layouts.
 */
export declare function classicCollideInto(bb: Float64Array, movement: Float64Array, colliders: Float64Array, colliderCount: number, output: Float64Array): void

/**
 * Low-overhead classic collision ABI. The single Float64Array contains:
 * [colliderCount, box(6), movement/result(3), colliders(6 * capacity)].
 */
export declare function classicCollidePacked(workspace: Float64Array): void

/** Version of the native ABI. Useful when diagnosing a mismatched prebuild. */
export declare function nativeAbiVersion(): number

/**
 * Resolve many independent Botcraft collision queries with one Node-API crossing.
 * Each query occupies 6 AABB doubles, 3 movement doubles, and two u32 range
 * entries (collider start and collider count). Colliders are packed as AABBs.
 */
export declare function voxelCollideBatchInto(boxes: Float64Array, movements: Float64Array, colliders: Float64Array, colliderRanges: Uint32Array, output: Float64Array): void

/** Resolve Botcraft/vanilla voxel-shape movement using its epsilon semantics. */
export declare function voxelCollideInto(bb: Float64Array, movement: Float64Array, colliders: Float64Array, colliderCount: number, output: Float64Array): void

/**
 * Low-overhead Botcraft collision ABI. Layout matches
 * `classic_collide_packed`, and movement is overwritten with the result.
 */
export declare function voxelCollidePacked(workspace: Float64Array): void
